services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # Remove the target line for simpler build
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/connect-plus.db
    volumes:
      # persist your SQLite database on the host
      - ./data:/app/data
    restart: unless-stopped
    # Add health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s